apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: istio-proxies-monitor
    namespace: rest-api-with-mesh
  spec:
    podMetricsEndpoints:
    - interval: 30s
      path: /stats/prometheus
      relabelings:
      - action: keep
        regex: istio-proxy
        sourceLabels:
        - __meta_kubernetes_pod_container_name
      - action: keep
        sourceLabels:
        - __meta_kubernetes_pod_annotationpresent_prometheus_io_scrape
      - action: replace
        regex: (\\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
        replacement: '[$2]:$1'
        sourceLabels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        targetLabel: __address__
      - action: replace
        regex: (\\d+);((([0-9]+?)(\.|$)){4})
        replacement: $2:$1
        sourceLabels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        targetLabel: __address__
      - action: replace
        regex: (.+);.*|.*;(.+)
        replacement: ${1}${2}
        separator: ;
        sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        - __meta_kubernetes_pod_label_app
        targetLabel: app
      - action: replace
        regex: (.+);.*|.*;(.+)
        replacement: ${1}${2}
        separator: ;
        sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_version
        - __meta_kubernetes_pod_label_version
        targetLabel: version
      - action: replace
        sourceLabels:
        - __meta_kubernetes_namespace
        targetLabel: namespace
      - action: replace
        replacement: ossm-3
        targetLabel: mesh_id
    selector:
      matchExpressions:
      - key: istio-prometheus-ignore
        operator: DoesNotExist
kind: List
metadata: {}
